config/routes.rb
Depot::Application.routes.draw do
  get "admin/index"
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"

  resources :users

  get "store/index"

  resources :products
  resources :line_items
  resources :carts
  resources :orders
    
  resources :products do 
    get :who_bought, :on => :member
    put :clone_product, :on => :member
  end
  
  get 'admin' => 'admin#index'
  controller :sessions do 
    get 'login' => :new 
    post 'login' => :create 
    delete 'logout' => :destroy
    get 'logout' => :destroy
  end
  

  root :to => 'store#index', :as => 'store'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pragprog Books Online Store</title>
<!-- START:stylesheet -->
  <%= stylesheet_link_tag "scaffold" %>
  <%= stylesheet_link_tag "depot", :media => "all" %><!-- <label id="code.slt"/> -->
<!-- END:stylesheet -->
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %><!-- <label id="code.csrf"/> -->
</head>

<body id="store">
  <div id="banner">
    <%= image_tag("logo.png") %>
    <%= @page_title || "Pragmatic Bookshelf" %><!-- <label id="code.depot.e.title"/> -->
  </div>
  <div id="columns">
    <div id="side">
	  <% if @cart %>
        <%= hidden_div_if(@cart.line_items.empty?, :id => "cart") do %> 
          <%= render @cart %>
        <% end %>
      <% end %>
      <a href="/">Home</a><br />
      <a href="http://www..../faq">Questions</a><br />

      <a href="http://www..../news">News</a><br />
      <a href="http://www..../contact">Contact</a><br />

      <br />
	  <% if session[:user_id] %> 
user	    <%= link_to 'Orders',	orders_path	%><br />
	    <%= link_to 'Products', products_path %><br />
	    <%= link_to 'Users',	users_path	%><br />
	    <br />
	    <!--%= button_to 'Logout', logout_path, :method => :delete	%--> 
	    <%= link_to 'Logout', logout_path %>
	  <% else %>
	    <%= link_to 'Login', login_path %>
	  <% end %>
    </div>

    <div id="main">
      <%= yield %><!-- <label id="code.depot.e.include"/> -->
    </div>
  </div>
  <p>Current Time: <%= @current_time %></p>
</body>
</html>